[build]
  # Global build settings here

[build.environment]
  # Global environment variables here

[[build]]
  dir = "bluff-frontend"
  publish = "bluff-frontend/build"
  command = "npm --prefix bluff-frontend run build"

[build.environment]
  # Environment variables specific to front-end here

[[build]]
  dir = "bluff-backend"
  base = "bluff-backend"
  command = "npm --prefix bluff-backend run build"

[build.environment]
  # Environment variables specific to back-end here
